# Generated by Django 4.0.1 on 2022-08-26 18:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('catchy', models.TextField()),
                ('picture', models.ImageField(default='me.jpg', upload_to='pics')),
                ('posted', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('publication', models.ManyToManyField(to='account.Publication')),
                ('reference', models.ManyToManyField(to='account.Reference')),
                ('topic', models.ManyToManyField(to='account.Topic')),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
    ]
