# Generated by Django 4.0.1 on 2022-08-27 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_topic_color_topic_short_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='logo',
            field=models.FileField(default='me.jpg', upload_to='pics', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
